[2025-04-24T21:04:19.540+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:19.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:04:19.548+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:04:19.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:19.670+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:04:19.656+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:04:19.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:19.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.212 seconds
[2025-04-24T21:04:50.298+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:50.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:04:50.308+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:04:50.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:50.427+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:04:50.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:04:50.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:04:50.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.206 seconds
[2025-04-24T21:05:21.072+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:21.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:05:21.081+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:05:21.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:21.232+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:05:21.219+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:05:21.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:21.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.228 seconds
[2025-04-24T21:05:51.857+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:51.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:05:51.863+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:05:51.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:51.941+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:05:51.923+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:05:51.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:05:51.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.145 seconds
[2025-04-24T21:06:22.731+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:22.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:06:22.739+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:06:22.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:22.892+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:06:22.869+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:06:22.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:22.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.252 seconds
[2025-04-24T21:06:53.479+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:53.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:06:53.483+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:06:53.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:53.584+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:06:53.570+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:06:53.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:06:53.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.165 seconds
[2025-04-24T21:07:24.360+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:24.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:07:24.366+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:07:24.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:24.481+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:07:24.461+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:07:24.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:24.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.194 seconds
[2025-04-24T21:07:55.118+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:55.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:07:55.129+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:07:55.127+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:55.269+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:07:55.248+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:07:55.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:07:55.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.235 seconds
[2025-04-24T21:08:25.979+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:25.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:08:25.990+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:08:25.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:26.154+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:08:26.121+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:08:26.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:26.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.248 seconds
[2025-04-24T21:08:56.819+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:56.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:08:56.833+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:08:56.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:57.025+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:08:56.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:08:57.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:08:57.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.313 seconds
[2025-04-24T21:09:27.950+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:27.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:09:27.957+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:09:27.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:28.102+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:09:28.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:09:28.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:28.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.243 seconds
[2025-04-24T21:09:58.582+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:58.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:09:58.595+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:09:58.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:58.746+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:09:58.724+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:09:58.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:09:58.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.236 seconds
[2025-04-24T21:10:29.572+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:10:29.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:10:29.579+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:10:29.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:10:29.704+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:10:29.685+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:10:29.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:10:29.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.203 seconds
[2025-04-24T21:11:00.191+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:00.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:11:00.197+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:11:00.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:00.316+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:11:00.295+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:11:00.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:00.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.199 seconds
[2025-04-24T21:11:31.014+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:31.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:11:31.019+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:11:31.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:31.116+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:11:31.099+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:11:31.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:11:31.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.172 seconds
[2025-04-24T21:12:01.671+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:01.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:12:01.676+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:12:01.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:01.759+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:12:01.746+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:12:01.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:01.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
[2025-04-24T21:12:32.528+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:32.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:12:32.535+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:12:32.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:32.618+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:12:32.604+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:12:32.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:12:32.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.153 seconds
[2025-04-24T21:13:03.313+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:03.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:13:03.324+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:13:03.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:03.490+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:13:03.478+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:13:03.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:03.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.249 seconds
[2025-04-24T21:13:34.211+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:34.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:13:34.225+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:13:34.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:34.368+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:13:34.348+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:13:34.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:13:34.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.259 seconds
[2025-04-24T21:14:05.004+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:05.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:14:05.014+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:14:05.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:05.165+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:14:05.140+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:14:05.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:05.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.230 seconds
[2025-04-24T21:14:35.864+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:35.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:14:35.871+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:14:35.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:36.007+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:14:35.986+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:14:36.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:14:36.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.219 seconds
[2025-04-24T21:15:06.533+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:06.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:15:06.544+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:15:06.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:06.720+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:15:06.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:15:06.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:06.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.271 seconds
[2025-04-24T21:15:37.446+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:37.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:15:37.453+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:15:37.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:37.568+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:15:37.550+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:15:37.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:15:37.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.183 seconds
[2025-04-24T21:16:08.168+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:16:08.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:16:08.175+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:16:08.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:16:08.289+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:16:08.269+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:16:08.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:16:08.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.186 seconds
[2025-04-24T21:22:12.510+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:12.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:22:12.516+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:22:12.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:12.607+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:22:12.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:22:12.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:12.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.161 seconds
[2025-04-24T21:22:43.109+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:43.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:22:43.117+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:22:43.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:43.232+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:22:43.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:22:43.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:22:43.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.191 seconds
[2025-04-24T21:23:13.902+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:13.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:23:13.910+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:23:13.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:14.046+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:23:14.026+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:23:14.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:14.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.273 seconds
[2025-04-24T21:23:44.723+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:44.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:23:44.731+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:23:44.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:44.936+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:23:44.900+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:23:44.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:23:45.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.306 seconds
[2025-04-24T21:24:15.673+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:15.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:24:15.689+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:24:15.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:15.847+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:24:15.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:24:15.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:15.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.289 seconds
[2025-04-24T21:24:46.552+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:46.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:24:46.561+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:24:46.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:46.673+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:24:46.654+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:24:46.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:24:46.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.221 seconds
[2025-04-24T21:25:17.519+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:25:17.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-24T21:25:17.534+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:25:17.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:25:17.709+0000] {logging_mixin.py:188} INFO - [2025-04-24T21:25:17.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-24T21:25:17.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-24T21:25:17.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.290 seconds
