[2025-04-25T13:53:50.454+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:53:50.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T13:53:50.459+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:53:50.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:53:50.545+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:53:50.536+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T13:53:50.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:53:50.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.138 seconds
[2025-04-25T13:54:25.525+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:25.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T13:54:25.552+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:54:25.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:25.755+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:54:25.725+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T13:54:25.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:25.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.624 seconds
[2025-04-25T13:54:56.280+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:56.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T13:54:56.288+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:54:56.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:56.337+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:54:56.330+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T13:54:56.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:54:56.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.124 seconds
[2025-04-25T13:55:26.699+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:55:26.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T13:55:26.705+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:55:26.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:55:26.822+0000] {logging_mixin.py:188} INFO - [2025-04-25T13:55:26.800+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 13, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T13:55:26.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T13:55:26.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.216 seconds
[2025-04-25T17:11:01.231+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:01.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:11:01.239+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:11:01.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:01.368+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:11:01.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:11:01.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:01.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.203 seconds
[2025-04-25T17:11:31.605+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:31.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:11:31.613+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:11:31.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:31.721+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:11:31.709+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:11:31.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:11:31.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.183 seconds
[2025-04-25T17:12:02.084+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:02.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:12:02.094+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:12:02.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:02.224+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:12:02.206+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:12:02.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:02.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.215 seconds
[2025-04-25T17:12:32.592+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:32.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:12:32.601+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:12:32.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:32.739+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:12:32.722+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:12:32.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:12:32.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.252 seconds
[2025-04-25T17:13:03.138+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:03.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:13:03.149+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:13:03.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:03.258+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:13:03.244+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:13:03.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:03.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.195 seconds
[2025-04-25T17:13:33.636+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:33.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:13:33.644+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:13:33.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:33.745+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:13:33.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:13:33.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:13:33.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.176 seconds
[2025-04-25T17:14:04.089+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:04.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:14:04.095+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:14:04.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:04.205+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:14:04.191+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:14:04.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:04.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.185 seconds
[2025-04-25T17:14:34.527+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:34.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:14:34.532+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:14:34.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:34.619+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:14:34.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:14:34.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:14:34.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
[2025-04-25T17:15:05.540+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:05.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:15:05.546+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:15:05.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:05.626+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:15:05.617+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:15:05.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:05.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.143 seconds
[2025-04-25T17:15:36.033+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:36.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:15:36.040+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:15:36.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:36.155+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:15:36.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:15:36.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:15:36.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.179 seconds
[2025-04-25T17:16:06.477+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:06.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:16:06.481+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:16:06.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:06.536+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:16:06.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:16:06.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:06.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.108 seconds
[2025-04-25T17:16:36.824+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:36.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:16:36.833+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:16:36.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:36.914+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:16:36.905+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:16:36.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:16:36.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.142 seconds
[2025-04-25T17:17:07.192+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:07.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:17:07.198+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:17:07.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:07.279+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:17:07.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:17:07.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:07.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.138 seconds
[2025-04-25T17:17:37.585+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:37.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:17:37.591+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:17:37.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:37.655+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:17:37.644+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:17:37.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:17:37.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.131 seconds
[2025-04-25T17:18:07.828+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:18:07.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:18:07.833+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:18:07.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:18:07.899+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:18:07.892+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:18:07.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:18:07.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.123 seconds
[2025-04-25T17:58:51.732+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:58:51.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:58:51.738+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:58:51.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:58:51.844+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:58:51.827+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:58:51.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:58:51.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.193 seconds
[2025-04-25T17:59:22.665+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:22.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:59:22.672+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:59:22.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:22.823+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:59:22.802+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:59:22.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:22.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.228 seconds
[2025-04-25T17:59:53.495+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:53.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T17:59:53.500+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:59:53.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:53.547+0000] {logging_mixin.py:188} INFO - [2025-04-25T17:59:53.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T17:59:53.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T17:59:53.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.105 seconds
[2025-04-25T18:00:24.532+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:24.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:00:24.539+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:00:24.538+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:24.639+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:00:24.623+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:00:24.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:24.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.175 seconds
[2025-04-25T18:00:55.494+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:55.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:00:55.503+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:00:55.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:55.598+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:00:55.584+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:00:55.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:00:55.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.181 seconds
[2025-04-25T18:01:26.461+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:26.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:01:26.469+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:01:26.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:26.335+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:01:26.314+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:01:26.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:26.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.202 seconds
[2025-04-25T18:01:57.099+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:57.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:01:57.107+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:01:57.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:57.244+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:01:57.227+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:01:57.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:01:57.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.214 seconds
[2025-04-25T18:02:28.186+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:28.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:02:28.196+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:02:28.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:28.364+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:02:28.338+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:02:28.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:28.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.328 seconds
[2025-04-25T18:02:59.040+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:59.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:02:59.047+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:02:59.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:59.124+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:02:59.114+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:02:59.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:02:59.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.162 seconds
[2025-04-25T18:03:29.891+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:03:29.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:03:29.901+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:03:29.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:03:30.044+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:03:30.028+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:03:30.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:03:30.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.217 seconds
[2025-04-25T18:04:01.118+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:01.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:04:01.124+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:04:01.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:01.206+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:04:01.196+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:04:01.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:01.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.145 seconds
[2025-04-25T18:04:31.506+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:31.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:04:31.521+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:04:31.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:31.605+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:04:31.594+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:04:31.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:04:31.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
[2025-04-25T18:05:02.370+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:02.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:05:02.382+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:05:02.381+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:02.556+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:05:02.533+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:05:02.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:02.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.271 seconds
[2025-04-25T18:05:32.949+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:32.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:05:32.961+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:05:32.960+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:33.116+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:05:33.091+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:05:33.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:05:33.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.262 seconds
[2025-04-25T18:06:03.793+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:03.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:06:03.799+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:06:03.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:03.857+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:06:03.850+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:06:03.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:03.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.122 seconds
[2025-04-25T18:06:34.676+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:34.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:06:34.684+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:06:34.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:34.780+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:06:34.764+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:06:34.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:06:34.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.176 seconds
[2025-04-25T18:07:05.621+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:05.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:07:05.629+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:07:05.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:05.728+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:07:05.714+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:07:05.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:05.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.182 seconds
[2025-04-25T18:07:36.409+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:36.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:07:36.415+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:07:36.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:36.608+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:07:36.592+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:07:36.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:07:36.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.283 seconds
[2025-04-25T18:08:06.958+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:06.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:08:06.964+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:08:06.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:07.054+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:08:07.043+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:08:07.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:07.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.167 seconds
[2025-04-25T18:08:37.760+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:37.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:08:37.767+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:08:37.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:37.859+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:08:37.848+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:08:37.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:08:37.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
[2025-04-25T18:29:02.728+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:02.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:29:02.736+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:29:02.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:02.848+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:29:02.832+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:29:02.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:02.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.166 seconds
[2025-04-25T18:29:33.554+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:33.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:29:33.563+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:29:33.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:33.654+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:29:33.639+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:29:33.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:29:33.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.209 seconds
[2025-04-25T18:30:04.398+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:04.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:30:04.407+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:30:04.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:04.494+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:30:04.483+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:30:04.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:04.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.163 seconds
[2025-04-25T18:30:35.460+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:35.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:30:35.467+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:30:35.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:35.573+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:30:35.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:30:35.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:30:35.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.175 seconds
[2025-04-25T18:31:06.343+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:06.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:31:06.350+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:31:06.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:06.437+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:31:06.424+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:31:06.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:06.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.170 seconds
[2025-04-25T18:31:37.264+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:37.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:31:37.270+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:31:37.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:37.372+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:31:37.353+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:31:37.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:31:37.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.178 seconds
[2025-04-25T18:32:08.057+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:08.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:32:08.066+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:32:08.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:08.188+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:32:08.170+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:32:08.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:08.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.208 seconds
[2025-04-25T18:32:39.045+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:39.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:32:39.054+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:32:39.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:39.177+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:32:39.158+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:32:39.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:32:39.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.209 seconds
[2025-04-25T18:33:09.901+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:09.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:33:09.906+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:33:09.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:09.968+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:33:09.958+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:33:09.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:10.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.129 seconds
[2025-04-25T18:33:40.836+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:40.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:33:40.842+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:33:40.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:40.942+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:33:40.926+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:33:40.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:33:40.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.168 seconds
[2025-04-25T18:34:11.263+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:11.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:34:11.270+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:34:11.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:11.353+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:34:11.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:34:11.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:11.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.147 seconds
[2025-04-25T18:34:42.030+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:42.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:34:42.035+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:34:42.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:42.096+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:34:42.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:34:42.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:34:42.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.117 seconds
[2025-04-25T18:38:21.206+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:21.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:38:21.213+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:38:21.212+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:21.315+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:38:21.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:38:21.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:21.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.165 seconds
[2025-04-25T18:38:52.041+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:52.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T18:38:52.052+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:38:52.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:52.173+0000] {logging_mixin.py:188} INFO - [2025-04-25T18:38:52.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T18:38:52.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T18:38:52.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.200 seconds
[2025-04-25T21:12:39.197+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:12:39.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:12:39.203+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:12:39.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:12:39.323+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:12:39.305+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:12:39.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:12:39.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.187 seconds
[2025-04-25T21:13:09.908+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:09.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:13:09.915+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:13:09.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:10.013+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:13:09.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:13:10.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:10.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.171 seconds
[2025-04-25T21:13:40.795+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:40.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:13:40.802+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:13:40.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:40.908+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:13:40.897+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:13:40.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:13:40.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.176 seconds
[2025-04-25T21:14:11.679+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:11.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:14:11.687+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:14:11.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:11.781+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:14:11.772+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:14:11.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:11.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.162 seconds
[2025-04-25T21:14:42.458+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:42.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:14:42.465+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:14:42.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:42.544+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:14:42.530+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:14:42.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:14:42.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.145 seconds
[2025-04-25T21:36:22.569+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:22.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:36:22.576+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:36:22.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:22.657+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:36:22.641+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:36:22.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:22.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.169 seconds
[2025-04-25T21:36:53.308+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:53.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:36:53.315+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:36:53.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:53.406+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:36:53.395+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:36:53.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:36:53.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.159 seconds
[2025-04-25T21:37:24.454+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:24.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:37:24.462+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:37:24.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:24.585+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:37:24.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:37:24.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:24.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.201 seconds
[2025-04-25T21:37:55.098+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:55.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:37:55.107+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:37:55.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:55.216+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:37:55.203+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:37:55.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:37:55.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.185 seconds
[2025-04-25T21:38:26.067+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:26.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:38:26.075+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:38:26.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:26.190+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:38:26.175+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:38:26.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:26.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.186 seconds
[2025-04-25T21:38:56.848+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:56.850+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:38:56.853+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:38:56.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:56.954+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:38:56.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:38:56.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:38:56.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.151 seconds
[2025-04-25T21:39:27.714+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:27.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:39:27.720+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:39:27.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:27.816+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:39:27.803+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:39:27.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:27.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.163 seconds
[2025-04-25T21:39:58.490+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:58.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:39:58.495+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:39:58.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:58.553+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:39:58.546+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:39:58.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:39:58.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.110 seconds
[2025-04-25T21:40:29.602+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:40:29.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:40:29.608+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:40:29.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:40:29.707+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:40:29.697+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:40:29.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:40:29.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.168 seconds
[2025-04-25T21:41:00.554+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:00.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:41:00.561+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:41:00.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:00.681+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:41:00.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:41:00.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:00.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.199 seconds
[2025-04-25T21:41:31.521+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:31.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:41:31.526+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:41:31.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:31.633+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:41:31.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:41:31.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:41:31.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.164 seconds
[2025-04-25T21:42:02.185+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:02.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:42:02.190+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:42:02.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:02.270+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:42:02.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:42:02.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:02.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.140 seconds
[2025-04-25T21:42:33.261+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:33.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:42:33.269+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:42:33.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:33.368+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:42:33.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:42:33.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:42:33.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.167 seconds
[2025-04-25T21:43:04.072+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:04.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:43:04.077+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:43:04.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:04.199+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:43:04.187+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:43:04.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:04.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.193 seconds
[2025-04-25T21:43:34.934+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:34.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:43:34.940+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:43:34.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:35.012+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:43:35.002+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:43:35.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:43:35.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.130 seconds
[2025-04-25T21:44:05.913+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:05.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:44:05.918+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:44:05.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:06.008+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:44:05.991+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:44:06.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:06.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.153 seconds
[2025-04-25T21:44:36.970+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:36.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:44:36.978+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:44:36.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:37.129+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:44:37.108+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:44:37.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:44:37.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.224 seconds
[2025-04-25T21:45:07.753+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:07.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:45:07.762+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:45:07.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:07.864+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:45:07.846+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:45:07.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:07.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.171 seconds
[2025-04-25T21:45:38.590+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:38.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:45:38.598+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:45:38.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:38.715+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:45:38.699+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:45:38.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:45:38.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.200 seconds
[2025-04-25T21:46:08.948+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:08.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:46:08.956+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:46:08.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:09.069+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:46:09.055+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:46:09.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:09.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.186 seconds
[2025-04-25T21:46:40.126+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:40.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:46:40.132+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:46:40.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:40.250+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:46:40.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:46:40.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:46:40.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.184 seconds
[2025-04-25T21:47:10.956+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:10.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:47:10.961+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:47:10.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:11.095+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:47:11.081+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:47:11.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:11.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.213 seconds
[2025-04-25T21:47:41.867+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:41.870+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:47:41.872+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:47:41.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:42.000+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:47:41.985+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:47:42.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:47:42.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.189 seconds
[2025-04-25T21:48:12.808+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:12.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:48:12.816+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:48:12.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:12.931+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:48:12.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:48:12.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:12.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.191 seconds
[2025-04-25T21:48:43.636+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:43.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:48:43.645+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:48:43.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:43.758+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:48:43.745+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:48:43.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:48:43.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.192 seconds
[2025-04-25T21:49:14.477+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:14.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:49:14.489+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:49:14.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:14.655+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:49:14.632+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:49:14.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:14.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.274 seconds
[2025-04-25T21:49:45.170+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:45.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:49:45.179+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:49:45.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:45.269+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:49:45.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:49:45.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:49:45.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.153 seconds
[2025-04-25T21:50:16.035+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:16.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:50:16.040+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:50:16.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:16.116+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:50:16.107+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:50:16.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:16.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.143 seconds
[2025-04-25T21:50:46.901+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:46.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:50:46.907+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:50:46.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:47.006+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:50:46.993+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:50:47.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:50:47.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.155 seconds
[2025-04-25T21:51:17.307+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:17.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:51:17.316+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:51:17.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:17.478+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:51:17.459+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:51:17.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:17.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.304 seconds
[2025-04-25T21:51:48.464+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:48.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:51:48.471+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:51:48.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:48.553+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:51:48.541+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:51:48.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:51:48.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.160 seconds
[2025-04-25T21:52:19.296+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:19.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:52:19.301+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:52:19.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:19.342+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:52:19.336+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:52:19.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:19.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.101 seconds
[2025-04-25T21:52:49.952+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:49.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:52:49.956+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:52:49.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:50.065+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:52:50.055+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:52:50.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:52:50.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
[2025-04-25T21:53:20.781+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:20.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:53:20.788+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:53:20.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:20.974+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:53:20.948+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:53:20.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:21.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.277 seconds
[2025-04-25T21:53:51.464+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:51.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow_integration.py for tasks to queue
[2025-04-25T21:53:51.469+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:53:51.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:51.559+0000] {logging_mixin.py:188} INFO - [2025-04-25T21:53:51.544+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/airflow_integration.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_integration.py", line 18, in <module>
    from multimodal_rag_system import (
ImportError: cannot import name 'initialize_system' from 'multimodal_rag_system' (unknown location)
[2025-04-25T21:53:51.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_integration.py
[2025-04-25T21:53:51.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow_integration.py took 0.157 seconds
